### ISSUE TITLE
Current Rocketchat version shows white input message box

### ISSUE THREAD

**Issue by stefanandres** [0x0049/Rocket.Chat.Dark#1]
Hey,
I'm new to this; I'd like to use your theme, but the input message box seems a little off-colored:

<img width="1113" alt="screen shot 2018-02-01 at 19 15 45" src="https://user-images.githubusercontent.com/2674469/35695298-585d7b9a-0784-11e8-9884-ec68cb0fa2e1.png">

**Comment by eryg-kai** [comment]
Thanks for the interest! Actually there are so many things to fix for the latest version of Rocket.Chat that I'm planning on re-skinning it from scratch. I won't be getting to it for a while though.

If you want a quick fix for the border color you could create a `custom.styl` file in the `src` folder with the following contents:

```
@import "dark"

.rc-message-box__container 
	border-color mix(#fff, chat-bg, 10%)
```

That should do it, although I haven't tested it.

**Comment by 0E800** [comment]
FYI - Administration panel does not match theme. Looking forward to your update.

**Comment by DoM1niC** [comment]
Any progress on this stuff ??? The new UI have to configure with the new Sidebar etc., I love this theme <3 but on the newest Version of RocketChat incompatible :(

**Comment by eryg-kai** [comment]
I finally found some time to work on this, got probably around 70-80% of it done and I should finish up some time tomorrow (probably later in the evening).

**Comment by eryg-kai** [comment]
Released a new version.
