### ISSUE TITLE
update link in project description

### ISSUE THREAD

**Issue by senpl** [0x0049/Rocket.Chat.Dark#10]
Probably actual link is https://www.0x0049.com/projects/Rocket.Chat.Dark/ old not work for me.

**Comment by eryg-kai** [comment]
Thanks for the report! Are you talking about this link: http://0x0049.link/rocket.chat.dark in the project's GitHub description? That one should just redirect to https://www.0x0049.com/projects/Rocket.Chat.Dark/.

**Comment by senpl** [comment]
Now it works for me. But in not worked 5 days ago.
