### ISSUE TITLE
Problems building with nodejs v10

### ISSUE THREAD

**Issue by jodizzle** [0x0049/Rocket.Chat.Dark#12]
Trying `npm run build` with nodejs v10 (I'm on nodejs v10.11.0 specifically) seems to run into trouble:
```
╰─$ npm run build

> Rocket.Chat.Dark@2.0.4 build /home/jodizzle/gitstuff/Rocket.Chat.Dark
> gulp

gulp[14322]: ../src/node_contextify.cc:628:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x55f3c222bbc1 node::Abort() [gulp]
 2: 0x55f3c222bcbb  [gulp]
 3: 0x55f3c2261b6b node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0x55f3c248edef  [gulp]
 5: 0x55f3c248f4df  [gulp]
 6: 0xa954345c01d
[1]    14311 abort (core dumped)  npm run build
```
After looking [here](https://stackoverflow.com/questions/50620673/gulp-task-issue-with-nodejs-v10-3-0-src-node-contextify-cc629-assertion-arg) and [here](https://github.com/gulpjs/gulp/issues/2162), the issue seems to be rooted in the 'natives' package.

One way to fix this is to just `npm install` in such a way that it auto-updates `package.json` and `package-lock.json`.  That's what I've done on a branch: https://github.com/jodizzle/Rocket.Chat.Dark/commits/fix/nodejs-10, and it seems to fix the issue.  I could PR that, but I was thinking maybe a more deliberate upgrade of packages would be preferable?  I'm not super familiar with npm and nodejs.

**Comment by eryg-kai** [comment]
Thanks for the report! I think tonight I'll upgrade all the packages and make sure they work. GitHub says there are vulnerabilities in some of the packages anyway (probably not a huge deal though since they're only used to build the CSS).
