### ISSUE TITLE
Makrdown tables are still "light"

### ISSUE THREAD

**Issue by michaelknigge** [0x0049/Rocket.Chat.Dark#16]
Hi,

when using tables (formatted with the markdown formatter "marked") the tables are still light. It would be great if they would also be styled dark.

Thanks,
Michael 

![dark-theme-markdown-tables](https://user-images.githubusercontent.com/7010114/49374034-6157ba00-f700-11e8-89d6-58027ab0424f.png)

**Comment by eryg-kai** [comment]
Thanks for the bug!
