### ISSUE TITLE
Huge message spacing in 0.66.1

### ISSUE THREAD

**Issue by jodizzle** [0x0049/Rocket.Chat.Dark#7]
I just moved to 0.66.1, and it seems like there are some spacing issues:

![2018-07-05-162306_1081x217_scrot](https://user-images.githubusercontent.com/672268/42346256-0e735e4a-8070-11e8-87c0-4a048a996566.png)

Spacing was fine as of 0.66.0.

**Comment by cursey** [comment]
Hi, I've fixed this in PR #8.

**Comment by jodizzle** [comment]
@cursey Thanks for this!  I actually tried to `git diff 0.66.0 0.66.1` in a clone of the Rocket.Chat source to see what changed, but couldn't figure it out.  Regardless, your PR seems to work.

**Comment by eryg-kai** [comment]
Closing since I've merged @cursey's PR. Thanks again!
