### ISSUE TITLE
Directory font color issue

### ISSUE THREAD

**Issue by marcinkorzycki** [0x0049/Rocket.Chat.Dark#9]
Hey!

new css version installed - we have issue with font color on Directory page. Can you fix it?

![image](https://user-images.githubusercontent.com/24276423/42455927-e0186000-8393-11e8-953e-2c9fccdfa300.png)

![image](https://user-images.githubusercontent.com/24276423/42455985-fb4e7b84-8393-11e8-8d26-ffcc9d8758fc.png)

**Comment by Rik67** [comment]
This should fix it.
Change this:

>  .rc-table {
  color: #c2c3c5;
 }

To this:
> .rc-table, .rc-table-title {
  color: #c2c3c5;
}

**Comment by marcinkorzycki** [comment]
Works! Thank you! Please add it to official release :)

**Comment by eryg-kai** [comment]
Thanks for the bug report and the fix! I'll get it in tonight. Apologies for not being more prompt.

**Comment by eryg-kai** [comment]
This is now [fixed](https://github.com/0x0049/Rocket.Chat.Dark/commit/147f25b434a780f5dd0190c2bbc4571b301d8050) in master, along with the hover color. Thanks again.
